defaultStake: 10000
defaultFee: 2000
zenaChainId: 15001
irisChainId: iris-15001
contractsBranch: mardizzone/node-16
genesisContractsBranch: master
sprintSize:
  - "64"
blockNumber:
  - "0"
blockTime:
  - "2"
numOfZenaValidators: 3
numOfZenaSentries: 0
numOfZenaArchiveNodes: 0
numOfErigonValidators: 0
numOfErigonSentries: 0
numOfErigonArchiveNodes: 0
ethURL: http://ganache:9545
ethHostUser: ubuntu
devnetType: docker
zenaDockerBuildContext: "../../zena"
irisDockerBuildContext: "https://github.com/zenanetwork/iris.git#develop"
sprintSizeBlockNumber:
  - "0"
devnetZenaFlags: config,config,config
