#!/bin/bash
# This is a postinstallation script so the service can be configured and started when requested
#
sudo adduser --disabled-password --disabled-login --shell /usr/sbin/nologin --quiet --system --no-create-home --home /nonexistent zena
if [ -d "/var/lib/zena" ]
then
    echo "Directory /var/lib/zena exists."
else
    mkdir -p /var/lib/zena
    sudo chown -R zena /var/lib/zena
fi
sudo systemctl daemon-reload
