// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: internal/cli/server/proto/server.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ZenaClient is the client API for Zena service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZenaClient interface {
	PeersAdd(ctx context.Context, in *PeersAddRequest, opts ...grpc.CallOption) (*PeersAddResponse, error)
	PeersRemove(ctx context.Context, in *PeersRemoveRequest, opts ...grpc.CallOption) (*PeersRemoveResponse, error)
	PeersList(ctx context.Context, in *PeersListRequest, opts ...grpc.CallOption) (*PeersListResponse, error)
	PeersStatus(ctx context.Context, in *PeersStatusRequest, opts ...grpc.CallOption) (*PeersStatusResponse, error)
	ChainSetHead(ctx context.Context, in *ChainSetHeadRequest, opts ...grpc.CallOption) (*ChainSetHeadResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ChainWatch(ctx context.Context, in *ChainWatchRequest, opts ...grpc.CallOption) (Zena_ChainWatchClient, error)
	DebugPprof(ctx context.Context, in *DebugPprofRequest, opts ...grpc.CallOption) (Zena_DebugPprofClient, error)
	DebugBlock(ctx context.Context, in *DebugBlockRequest, opts ...grpc.CallOption) (Zena_DebugBlockClient, error)
}

type zenaClient struct {
	cc grpc.ClientConnInterface
}

func NewZenaClient(cc grpc.ClientConnInterface) ZenaClient {
	return &zenaClient{cc}
}

func (c *zenaClient) PeersAdd(ctx context.Context, in *PeersAddRequest, opts ...grpc.CallOption) (*PeersAddResponse, error) {
	out := new(PeersAddResponse)

	err := c.cc.Invoke(ctx, "/proto.Zena/PeersAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}

	return out, nil
}

func (c *zenaClient) PeersRemove(ctx context.Context, in *PeersRemoveRequest, opts ...grpc.CallOption) (*PeersRemoveResponse, error) {
	out := new(PeersRemoveResponse)

	err := c.cc.Invoke(ctx, "/proto.Zena/PeersRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}

	return out, nil
}

func (c *zenaClient) PeersList(ctx context.Context, in *PeersListRequest, opts ...grpc.CallOption) (*PeersListResponse, error) {
	out := new(PeersListResponse)

	err := c.cc.Invoke(ctx, "/proto.Zena/PeersList", in, out, opts...)
	if err != nil {
		return nil, err
	}

	return out, nil
}

func (c *zenaClient) PeersStatus(ctx context.Context, in *PeersStatusRequest, opts ...grpc.CallOption) (*PeersStatusResponse, error) {
	out := new(PeersStatusResponse)

	err := c.cc.Invoke(ctx, "/proto.Zena/PeersStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}

	return out, nil
}

func (c *zenaClient) ChainSetHead(ctx context.Context, in *ChainSetHeadRequest, opts ...grpc.CallOption) (*ChainSetHeadResponse, error) {
	out := new(ChainSetHeadResponse)

	err := c.cc.Invoke(ctx, "/proto.Zena/ChainSetHead", in, out, opts...)
	if err != nil {
		return nil, err
	}

	return out, nil
}

func (c *zenaClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)

	err := c.cc.Invoke(ctx, "/proto.Zena/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}

	return out, nil
}

func (c *zenaClient) ChainWatch(ctx context.Context, in *ChainWatchRequest, opts ...grpc.CallOption) (Zena_ChainWatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &Zena_ServiceDesc.Streams[0], "/proto.Zena/ChainWatch", opts...)
	if err != nil {
		return nil, err
	}

	x := &zenaChainWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}

	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}

	return x, nil
}

type Zena_ChainWatchClient interface {
	Recv() (*ChainWatchResponse, error)
	grpc.ClientStream
}

type zenaChainWatchClient struct {
	grpc.ClientStream
}

func (x *zenaChainWatchClient) Recv() (*ChainWatchResponse, error) {
	m := new(ChainWatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}

	return m, nil
}

func (c *zenaClient) DebugPprof(ctx context.Context, in *DebugPprofRequest, opts ...grpc.CallOption) (Zena_DebugPprofClient, error) {
	stream, err := c.cc.NewStream(ctx, &Zena_ServiceDesc.Streams[1], "/proto.Zena/DebugPprof", opts...)
	if err != nil {
		return nil, err
	}

	x := &zenaDebugPprofClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}

	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}

	return x, nil
}

type Zena_DebugPprofClient interface {
	Recv() (*DebugFileResponse, error)
	grpc.ClientStream
}

type zenaDebugPprofClient struct {
	grpc.ClientStream
}

func (x *zenaDebugPprofClient) Recv() (*DebugFileResponse, error) {
	m := new(DebugFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}

	return m, nil
}

func (c *zenaClient) DebugBlock(ctx context.Context, in *DebugBlockRequest, opts ...grpc.CallOption) (Zena_DebugBlockClient, error) {
	stream, err := c.cc.NewStream(ctx, &Zena_ServiceDesc.Streams[2], "/proto.Zena/DebugBlock", opts...)
	if err != nil {
		return nil, err
	}

	x := &zenaDebugBlockClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}

	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}

	return x, nil
}

type Zena_DebugBlockClient interface {
	Recv() (*DebugFileResponse, error)
	grpc.ClientStream
}

type zenaDebugBlockClient struct {
	grpc.ClientStream
}

func (x *zenaDebugBlockClient) Recv() (*DebugFileResponse, error) {
	m := new(DebugFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}

	return m, nil
}

// ZenaServer is the server API for Zena service.
// All implementations must embed UnimplementedZenaServer
// for forward compatibility
type ZenaServer interface {
	PeersAdd(context.Context, *PeersAddRequest) (*PeersAddResponse, error)
	PeersRemove(context.Context, *PeersRemoveRequest) (*PeersRemoveResponse, error)
	PeersList(context.Context, *PeersListRequest) (*PeersListResponse, error)
	PeersStatus(context.Context, *PeersStatusRequest) (*PeersStatusResponse, error)
	ChainSetHead(context.Context, *ChainSetHeadRequest) (*ChainSetHeadResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	ChainWatch(*ChainWatchRequest, Zena_ChainWatchServer) error
	DebugPprof(*DebugPprofRequest, Zena_DebugPprofServer) error
	DebugBlock(*DebugBlockRequest, Zena_DebugBlockServer) error
	mustEmbedUnimplementedZenaServer()
}

// UnimplementedZenaServer must be embedded to have forward compatible implementations.
type UnimplementedZenaServer struct {
}

func (UnimplementedZenaServer) PeersAdd(context.Context, *PeersAddRequest) (*PeersAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PeersAdd not implemented")
}
func (UnimplementedZenaServer) PeersRemove(context.Context, *PeersRemoveRequest) (*PeersRemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PeersRemove not implemented")
}
func (UnimplementedZenaServer) PeersList(context.Context, *PeersListRequest) (*PeersListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PeersList not implemented")
}
func (UnimplementedZenaServer) PeersStatus(context.Context, *PeersStatusRequest) (*PeersStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PeersStatus not implemented")
}
func (UnimplementedZenaServer) ChainSetHead(context.Context, *ChainSetHeadRequest) (*ChainSetHeadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChainSetHead not implemented")
}
func (UnimplementedZenaServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedZenaServer) ChainWatch(*ChainWatchRequest, Zena_ChainWatchServer) error {
	return status.Errorf(codes.Unimplemented, "method ChainWatch not implemented")
}
func (UnimplementedZenaServer) DebugPprof(*DebugPprofRequest, Zena_DebugPprofServer) error {
	return status.Errorf(codes.Unimplemented, "method DebugPprof not implemented")
}
func (UnimplementedZenaServer) DebugBlock(*DebugBlockRequest, Zena_DebugBlockServer) error {
	return status.Errorf(codes.Unimplemented, "method DebugBlock not implemented")
}
func (UnimplementedZenaServer) mustEmbedUnimplementedZenaServer() {}

// UnsafeZenaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZenaServer will
// result in compilation errors.
type UnsafeZenaServer interface {
	mustEmbedUnimplementedZenaServer()
}

func RegisterZenaServer(s grpc.ServiceRegistrar, srv ZenaServer) {
	s.RegisterService(&Zena_ServiceDesc, srv)
}

func _Zena_PeersAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeersAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}

	if interceptor == nil {
		return srv.(ZenaServer).PeersAdd(ctx, in)
	}

	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Zena/PeersAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenaServer).PeersAdd(ctx, req.(*PeersAddRequest))
	}

	return interceptor(ctx, in, info, handler)
}

func _Zena_PeersRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeersRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}

	if interceptor == nil {
		return srv.(ZenaServer).PeersRemove(ctx, in)
	}

	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Zena/PeersRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenaServer).PeersRemove(ctx, req.(*PeersRemoveRequest))
	}

	return interceptor(ctx, in, info, handler)
}

func _Zena_PeersList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeersListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}

	if interceptor == nil {
		return srv.(ZenaServer).PeersList(ctx, in)
	}

	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Zena/PeersList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenaServer).PeersList(ctx, req.(*PeersListRequest))
	}

	return interceptor(ctx, in, info, handler)
}

func _Zena_PeersStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeersStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}

	if interceptor == nil {
		return srv.(ZenaServer).PeersStatus(ctx, in)
	}

	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Zena/PeersStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenaServer).PeersStatus(ctx, req.(*PeersStatusRequest))
	}

	return interceptor(ctx, in, info, handler)
}

func _Zena_ChainSetHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainSetHeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}

	if interceptor == nil {
		return srv.(ZenaServer).ChainSetHead(ctx, in)
	}

	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Zena/ChainSetHead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenaServer).ChainSetHead(ctx, req.(*ChainSetHeadRequest))
	}

	return interceptor(ctx, in, info, handler)
}

func _Zena_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}

	if interceptor == nil {
		return srv.(ZenaServer).Status(ctx, in)
	}

	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Zena/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenaServer).Status(ctx, req.(*StatusRequest))
	}

	return interceptor(ctx, in, info, handler)
}

func _Zena_ChainWatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChainWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}

	return srv.(ZenaServer).ChainWatch(m, &zenaChainWatchServer{stream})
}

type Zena_ChainWatchServer interface {
	Send(*ChainWatchResponse) error
	grpc.ServerStream
}

type zenaChainWatchServer struct {
	grpc.ServerStream
}

func (x *zenaChainWatchServer) Send(m *ChainWatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Zena_DebugPprof_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DebugPprofRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}

	return srv.(ZenaServer).DebugPprof(m, &zenaDebugPprofServer{stream})
}

type Zena_DebugPprofServer interface {
	Send(*DebugFileResponse) error
	grpc.ServerStream
}

type zenaDebugPprofServer struct {
	grpc.ServerStream
}

func (x *zenaDebugPprofServer) Send(m *DebugFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Zena_DebugBlock_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DebugBlockRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}

	return srv.(ZenaServer).DebugBlock(m, &zenaDebugBlockServer{stream})
}

type Zena_DebugBlockServer interface {
	Send(*DebugFileResponse) error
	grpc.ServerStream
}

type zenaDebugBlockServer struct {
	grpc.ServerStream
}

func (x *zenaDebugBlockServer) Send(m *DebugFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Zena_ServiceDesc is the grpc.ServiceDesc for Zena service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zena_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Zena",
	HandlerType: (*ZenaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PeersAdd",
			Handler:    _Zena_PeersAdd_Handler,
		},
		{
			MethodName: "PeersRemove",
			Handler:    _Zena_PeersRemove_Handler,
		},
		{
			MethodName: "PeersList",
			Handler:    _Zena_PeersList_Handler,
		},
		{
			MethodName: "PeersStatus",
			Handler:    _Zena_PeersStatus_Handler,
		},
		{
			MethodName: "ChainSetHead",
			Handler:    _Zena_ChainSetHead_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Zena_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChainWatch",
			Handler:       _Zena_ChainWatch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DebugPprof",
			Handler:       _Zena_DebugPprof_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DebugBlock",
			Handler:       _Zena_DebugBlock_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/cli/server/proto/server.proto",
}
