name: packager_deb

on:
  push:
    branches:
      - "master"
    paths:
      - "**"
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

jobs:
  build:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.23.6
      # Variables
      - name: Adding TAG to ENV
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: adding version
        run: |
          NUMERIC_VERSION=$( echo ${{ env.GIT_TAG }} | sed 's/[^0-9.]//g' ) 
          echo "VERSION=$NUMERIC_VERSION" >> $GITHUB_ENV

      - name: Cleaning repo
        run: make clean
      - name: Building for amd64
        run: make zena

      - name: Making directory structure
        run: mkdir -p packaging/deb/zena/usr/bin
      - name: Copying necessary files
        run: cp -rp build/bin/zena packaging/deb/zena/usr/bin/
      - name: Delete control file
        run: rm -rf packaging/deb/zena/DEBIAN/control

      # Control file creation
      - name: create control file
        run: |
          touch packaging/deb/zena/DEBIAN/control
          echo "Package: zena" >> packaging/deb/zena/DEBIAN/control
          echo "Version: ${{ env.VERSION }}" >> packaging/deb/zena/DEBIAN/control
          echo "Section: base" >> packaging/deb/zena/DEBIAN/control
          echo "Priority: optional" >> packaging/deb/zena/DEBIAN/control
          echo "Architecture: amd64" >> packaging/deb/zena/DEBIAN/control
          echo "Maintainer: devops@polygon.technology" >> packaging/deb/zena/DEBIAN/control
          echo "Description: zena binary package" >> packaging/deb/bzenaozenar/DEBIAN/control

      - name: Creating package for binary for zena ${{ env.ARCH }}
        run: cp -rp packaging/deb/zena packaging/deb/zena-${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: amd64

      - name: Running package build
        run: dpkg-deb --build --root-owner-group packaging/deb/zena-${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: amd64

      - name: Cleaning build directory for arm64 build
        run: make clean

      - name: Updating the apt-get
        run: sudo apt-get update -y

      - name: Adding requirements for cross compile
        run: sudo apt-get install g++-aarch64-linux-gnu gcc-aarch64-linux-gnu

      - name: delete amd64 control file
        run: rm -rf packaging/deb/zena/DEBIAN/control

      - name: Building zena for arm64
        run: GOARCH=arm64 GOOS=linux CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ CGO_ENABLED=1 go build -o build/bin/zena ./cmd/cli/main.go

      - name: Copying necessary binary post arm64 build
        run: cp -rp build/bin/zena packaging/deb/zena/usr/bin/

      # Control file for arm64 creation
      - name: create control file
        run: |
          touch packaging/deb/zena/DEBIAN/control
          echo "Package: zena" >> packaging/deb/zena/DEBIAN/control
          echo "Version: ${{ env.VERSION }}" >> packaging/deb/zena/DEBIAN/control
          echo "Section: base" >> packaging/deb/zena/DEBIAN/control
          echo "Priority: optional" >> packaging/deb/zena/DEBIAN/control
          echo "Architecture: arm64" >> packaging/deb/zena/DEBIAN/control
          echo "Maintainer: devops@polygon.technology" >> packaging/deb/zena/DEBIAN/control
          echo "Description: zena binary package" >> packaging/deb/zena/DEBIAN/control

      - name: Creating package for binary for zena ${{ env.ARCH }}
        run: cp -rp packaging/deb/zena packaging/deb/zena-${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: arm64

      - name: Running package build
        run: dpkg-deb --build --root-owner-group packaging/deb/zena-${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: arm64

      # Shasum
      - name: shasum the zena debian package
        run: cd packaging/deb/ && sha256sum zena-${{ env.GIT_TAG }}-${{ env.ARCH }}.deb > zena-${{ env.GIT_TAG }}-${{ env.ARCH }}.deb.checksum
        env:
          ARCH: amd64

      - name: shasum the zena debian package
        run: cd packaging/deb/ && sha256sum zena-${{ env.GIT_TAG }}-${{ env.ARCH }}.deb > zena-${{ env.GIT_TAG }}-${{ env.ARCH }}.deb.checksum
        env:
          ARCH: arm64

      - name: Release zena Packages
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.GIT_TAG }}
          prerelease: true
          files: |
            packaging/deb/zena**.deb
            packaging/deb/zena**.deb.checksum
